import {Button} from '@chakra-ui/button'
import {Heading, Text, VStack} from '@chakra-ui/layout'
import type {NextPage} from 'next'
import Head from 'next/head'
import Root from "../components/Root";
import { useTranslation } from '../utils/use-translation';

const localisation = {
    en: {
      title: 'Donate your yield to help'
    },
    fr: {
      title: 'Donnez votre rendement'
    }
  }

const Home: NextPage = () => {
    const translate = useTranslation(localisation)

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Root>
                <VStack spacing={4} mt={250}>
                    <Heading color='#fff' style={{fontWeight: 'bold', fontSize: 48}}>{translate('title')} {' '}
                        <span style={{color: '#FFD500'}}>Ukraine</span>
                    </Heading>
                    <Text color="#fff" style={{fontWeight: 'bold', fontSize: '96px'}}>₴1,234,567.00</Text>
                    <Button backgroundColor="#FFD500"
                            style={{ borderRadius: 25, height: 58, width: 194, marginTop: 50 }}>
                        Donate Now {'>'}
                    </Button>
                    <Button backgroundColor="#fff"
                            style={{ borderRadius: 25, height: 58, width: 251, marginTop: 20 }}>
                        Explore NFTs
                    </Button>
                </VStack>
            </Root>
        </div>
    )
}

export default Home
