import {Button} from '@chakra-ui/button'
import {Heading, Text, Spacer, Flex} from '@chakra-ui/layout'
import type {NextPage} from 'next'
import Head from 'next/head'
import Root from "../components/Root";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Root>
                <Flex direction={"column"} alignItems="center" >
                    <Heading color='#fff' style={{fontWeight: 'bold', fontSize: 48}}>Donate your yield to help {' '}
                        <span style={{color: '#FFD500'}}>Ukraine</span>
                    </Heading>
                    <Text color="#fff" style={{fontWeight: 'bold', fontSize: '96px'}}>₴1,234,567.00</Text>
                    <Button backgroundColor="#FFD500"
                            style={{ borderRadius: 25, height: 58, width: 194, marginTop: 50 }}>
                        Donate Now {'>'}
                    </Button>
                    <Button backgroundColor="#fff"
                            style={{ borderRadius: 25, height: 58, width: 251, marginTop: 20 }}>
                        Explore NFTs
                    </Button>
                </Flex>
            </Root>
        </div>
    )
}

export default Home
